### ISSUE TITLE
how to use  it?

### ISSUE THREAD

**Issue by Mohamed-moneim-said** [Earthquake-Project/EarthQuake-Haxe#3]
thank you for information, I opened this "D:\Downloads\EarthQuake-Haxe-master\EarthQuake-Haxe-master\src\haxe\EarthQuake.hxproj" and build it and Build succeeded without any error. but
**<h3>How use it?</h3>**

**Comment by Brian151** [comment]
currently, you can't do anything with it because it's massively incomplete
i've re-made now this whole thing two or three times and never once did i get to a use-able product
hopefully it will change this time

however, irl has made coding quite difficult lately...
i don't have time or i don't have energy, it sucks

**Comment by Mohamed-moneim-said** [comment]
ok
